/**
 * Official Institutional Financial Statement & Audit PDF Generator
 * Zero-Cost Client-Side Engine powered by jsPDF & jspdf-autotable.
 * Meets academic and club governance requirements for submission to
 * Faculty Coordinators, Student Welfare, and University Accounts.
 */

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { FinanceSheet, FinanceTransaction } from "@/types/models";

interface GenerateFinancePdfOptions {
  sheetTitle: string;
  sheet?: FinanceSheet | undefined;
  transactions: FinanceTransaction[];
  generatedByName: string;
  generatedByRole: string;
}

export function generateFinanceReportPdf({
  sheetTitle,
  sheet,
  transactions,
  generatedByName,
  generatedByRole,
}: GenerateFinancePdfOptions): void {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const incomes = transactions.filter((t) => t.type === "income");
  const expenses = transactions.filter((t) => t.type === "expense");

  const totalIncome = incomes.reduce((sum, t) => sum + Number(t.amount || 0), 0);
  const totalExpense = expenses.reduce((sum, t) => sum + Number(t.amount || 0), 0);
  const netBalance = totalIncome - totalExpense;

  const reportRef = `DSC-AUDIT-${Date.now().toString().slice(-6)}`;
  const dateStr = new Date().toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  // Top Institutional Header Border Accent
  doc.setFillColor(15, 23, 42); // Slate 900
  doc.rect(0, 0, pageWidth, 28, "F");

  doc.setFillColor(6, 182, 212); // Cyan accent strip
  doc.rect(0, 27, pageWidth, 1.5, "F");

  // University & Club Header Title
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("VELLORE INSTITUTE OF TECHNOLOGY (VIT) BHOPAL", pageWidth / 2, 10, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(203, 213, 225); // Slate 300
  doc.text("School of Computing Science & Engineering  |  Data Science Club (DSC)", pageWidth / 2, 16, { align: "center" });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(103, 232, 249); // Cyan 300
  doc.text("OFFICIAL FINANCIAL AUDIT & TREASURY DISBURSEMENT STATEMENT", pageWidth / 2, 22, { align: "center" });

  // Metadata Panel
  let currentY = 36;
  doc.setFillColor(248, 250, 252); // Slate 50
  doc.setDrawColor(226, 232, 240); // Slate 200
  doc.roundedRect(14, currentY, pageWidth - 28, 22, 2, 2, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  doc.text("AUDIT SCOPE / LEDGER:", 18, currentY + 6);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(51, 65, 85);
  doc.text(sheetTitle, 65, currentY + 6);

  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("AUDIT REPORT ID:", 18, currentY + 12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(51, 65, 85);
  doc.text(reportRef, 65, currentY + 12);

  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("DATE OF AUDIT:", 18, currentY + 18);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(51, 65, 85);
  doc.text(dateStr, 65, currentY + 18);

  // Right column of meta box
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("GENERATED BY:", 120, currentY + 6);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(51, 65, 85);
  doc.text(generatedByName, 155, currentY + 6);

  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("ROLE / AUTHORITY:", 120, currentY + 12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(51, 65, 85);
  doc.text(generatedByRole, 155, currentY + 12);

  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("VERIFICATION:", 120, currentY + 18);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(16, 185, 129); // Green
  doc.text("Official Record Verified", 155, currentY + 18);

  currentY += 28;

  // Executive Balance Metric Cards
  const cardWidth = (pageWidth - 28 - 8) / 3;

  // Card 1: Total Inflow
  doc.setFillColor(240, 253, 244); // Green 50
  doc.setDrawColor(187, 247, 208); // Green 200
  doc.roundedRect(14, currentY, cardWidth, 18, 2, 2, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(22, 101, 52);
  doc.text("TOTAL REVENUE / INFLOW", 18, currentY + 5);
  doc.setFontSize(12);
  doc.text(`INR ${totalIncome.toLocaleString("en-IN")}`, 18, currentY + 13);

  // Card 2: Total Outflow
  doc.setFillColor(255, 241, 242); // Rose 50
  doc.setDrawColor(254, 205, 211); // Rose 200
  doc.roundedRect(14 + cardWidth + 4, currentY, cardWidth, 18, 2, 2, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(159, 18, 57);
  doc.text("TOTAL EXPENDITURE / OUTFLOW", 14 + cardWidth + 8, currentY + 5);
  doc.setFontSize(12);
  doc.text(`INR ${totalExpense.toLocaleString("en-IN")}`, 14 + cardWidth + 8, currentY + 13);

  // Card 3: Net Balance
  const isSurplus = netBalance >= 0;
  doc.setFillColor(isSurplus ? 238 : 254, isSurplus ? 242 : 242, isSurplus ? 255 : 242); // Indigo or Amber
  doc.setDrawColor(isSurplus ? 199 : 254, isSurplus ? 210 : 215, isSurplus ? 254 : 170);
  doc.roundedRect(14 + (cardWidth + 4) * 2, currentY, cardWidth, 18, 2, 2, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(isSurplus ? 55 : 180, isSurplus ? 48 : 83, isSurplus ? 163 : 9);
  doc.text(isSurplus ? "NET SURPLUS BALANCE" : "NET DEFICIT BALANCE", 14 + (cardWidth + 4) * 2 + 4, currentY + 5);
  doc.setFontSize(12);
  doc.text(`INR ${Math.abs(netBalance).toLocaleString("en-IN")}`, 14 + (cardWidth + 4) * 2 + 4, currentY + 13);

  currentY += 24;

  // Section 1: Inflow Table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text("1. Schedule of Inflow & Revenue Sources", 14, currentY);

  const incomeTableBody = incomes.map((t) => [
    t.transactionDate || "-",
    t.category || "General",
    t.description || "-",
    t.paymentMode || "UPI",
    t.transactionRef || "-",
    `INR ${Number(t.amount || 0).toLocaleString("en-IN")}`,
  ]);

  autoTable(doc, {
    startY: currentY + 3,
    margin: { left: 14, right: 14 },
    head: [["Date", "Category", "Description", "Mode", "Reference / UTR", "Amount"]],
    body: incomeTableBody.length > 0 ? incomeTableBody : [["-", "No Inflow Recorded", "-", "-", "-", "INR 0"]],
    foot: [["Total Inflow", "", "", "", "", `INR ${totalIncome.toLocaleString("en-IN")}`]],
    theme: "striped",
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: "bold",
    },
    bodyStyles: {
      fontSize: 7.5,
      textColor: [51, 65, 85],
    },
    footStyles: {
      fillColor: [241, 245, 249],
      textColor: [15, 23, 42],
      fontStyle: "bold",
      fontSize: 8,
    },
    styles: { cellPadding: 2 },
  });

  // Calculate position after income table
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const lastTableDoc = doc as any;
  currentY = (lastTableDoc.lastAutoTable?.finalY || currentY + 30) + 8;

  // Check if we need page break before expenses
  if (currentY > pageHeight - 75) {
    doc.addPage();
    currentY = 20;
  }

  // Section 2: Expenditure Table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text("2. Itemized Expenditure & Disbursement Schedule", 14, currentY);

  const expenseTableBody = expenses.map((t) => [
    t.transactionDate || "-",
    t.category || "Misc",
    t.description || "-",
    t.paymentMode || "UPI",
    t.transactionRef || "N/A",
    t.billFileName ? "Attached" : "Self-Attested",
    `INR ${Number(t.amount || 0).toLocaleString("en-IN")}`,
  ]);

  autoTable(doc, {
    startY: currentY + 3,
    margin: { left: 14, right: 14 },
    head: [["Date", "Expense Head", "Description", "Mode", "Bill / Voucher Ref", "Receipt", "Amount"]],
    body: expenseTableBody.length > 0 ? expenseTableBody : [["-", "No Expenses Recorded", "-", "-", "-", "-", "INR 0"]],
    foot: [["Total Expenditure", "", "", "", "", "", `INR ${totalExpense.toLocaleString("en-IN")}`]],
    theme: "striped",
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: "bold",
    },
    bodyStyles: {
      fontSize: 7.5,
      textColor: [51, 65, 85],
    },
    footStyles: {
      fillColor: [241, 245, 249],
      textColor: [15, 23, 42],
      fontStyle: "bold",
      fontSize: 8,
    },
    styles: { cellPadding: 2 },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  currentY = (lastTableDoc.lastAutoTable?.finalY || currentY + 30) + 12;

  // Institutional Sign-off Block
  if (currentY > pageHeight - 55) {
    doc.addPage();
    currentY = 25;
  }

  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(203, 213, 225);
  doc.roundedRect(14, currentY, pageWidth - 28, 42, 2, 2, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(15, 23, 42);
  doc.text("INSTITUTIONAL AUDIT VERIFICATION & APPROVAL SIGN-OFF", 18, currentY + 6);

  const sigWidth = (pageWidth - 28 - 16) / 3;
  const sigY = currentY + 14;

  // Box 1: President / Treasurer
  doc.setDrawColor(203, 213, 225);
  doc.line(18, sigY + 16, 18 + sigWidth, sigY + 16);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(51, 65, 85);
  doc.text("Prepared & Reconciled By", 18, sigY + 20);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(100, 116, 139);
  doc.text("President / Treasurer, DSC", 18, sigY + 24);

  // Box 2: Faculty Coordinator
  const box2X = 18 + sigWidth + 8;
  doc.line(box2X, sigY + 16, box2X + sigWidth, sigY + 16);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(51, 65, 85);
  doc.text("Verified & Audited By", box2X, sigY + 20);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(100, 116, 139);
  doc.text("Faculty Coordinator, DSC", box2X, sigY + 24);

  // Box 3: Dean / Student Welfare
  const box3X = box2X + sigWidth + 8;
  doc.line(box3X, sigY + 16, box3X + sigWidth, sigY + 16);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(51, 65, 85);
  doc.text("Approved & Counter-Signed", box3X, sigY + 20);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(100, 116, 139);
  doc.text("Dean, SCSE / Student Welfare", box3X, sigY + 24);

  // Footer on all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(148, 163, 184); // Slate 400
    doc.text(
      `DSC VIT Bhopal | Financial Audit Report | Ref: ${reportRef} | Confidential Institutional Document`,
      14,
      pageHeight - 6,
    );
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - 14, pageHeight - 6, { align: "right" });
  }

  // Trigger browser download
  const cleanTitle = sheetTitle.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  doc.save(`DSC_Finance_Audit_${cleanTitle}_${Date.now()}.pdf`);
}
